# configuration for https://travis-ci.org/cpesch/RouteConverter
sudo: false
language: java
cache:
 directories:
   - $HOME/.m2
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
git:
  depth: 3
branches:
  only:
    - 2.18-maintenance
notifications:
  email:
  - support@routeconverter.com